### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

### ISSUE THREAD

**Issue by Oliwerix** [adimineman/1bitvm#6] opened 2023-01-30 19:18 UTC
When stdio is input, the vm crashes on UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

The input file is `example4.out` compiled from #5 using `./asm.py` 

## vm backtrace
      -4Traceback (most recent call last):
      File "/home/oliwerix/projects/1bitvm/./main.py", line 30, in <module>
        main()
      File "/home/oliwerix/projects/1bitvm/./main.py", line 26, in main
        virtual_machine.run(-1)
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 232, in run
        while self.step() and itr != 0:
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 249, in step
        self.opp1(adr0, adr1, meta)
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 275, in opp1
        self.ram.set(
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 139, in set
        self.evl_hooks(i, True, val)
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 128, in evl_hooks
        return self.hooks[(reg, to_regs)].evl(self, reg, to_regs, data)
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 52, in evl
        self.flush(that)
      File "/home/oliwerix/projects/1bitvm/oneb_vm.py", line 62, in flush
        print(out.to_bytes(1, "big").decode(), end="")
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

**Comment by adimineman** [comment] 2023-01-30 19:20
Not a bug, expected! Closing now

**Comment by adimineman** [comment] 2023-01-30 19:31
Apparently is a bug
#todo
[link to closing reply](https://github.com/adimineman/1bitvm/issues/6#issuecomment-1409206178) < fire this guy

**Comment by adimineman** [comment] 2023-01-30 19:31
The error is in decoding multi byte utf-8 sequences

**Comment by adimineman** [comment] 2023-01-30 19:35
https://github.com/adimineman/1bitvm/blob/d1f3fe3e7975dd89cd7a77e5cb3e1ff0d7a26ad5/oneb_vm.py#L55-L62
problem lies here

**Closed** 2023-01-30 21:32 UTC
Labels: bug
